### ISSUE TITLE
Windows plugins issue

### ISSUE THREAD

**Issue by botanicvelious** [peragro/peragro-at#36]
any ideas?

> C:\development\peragro\peragro-at>pt a ../peragro-test-files/mesh/blender/cube1.blend --store /tmp/peragro
Traceback (most recent call last):
  File "C:\Python351\Scripts\pt-script.py", line 11, in <module>
    load_entry_point('damn-at===0.0.0-development', 'console_scripts', 'pt')()
  File "C:\Python351\lib\site-packages\damn_at-0.0.0_development-py3.5.egg\damn_at\cli.py", line 349, in main
    args.func(args)
  File "C:\Python351\lib\site-packages\damn_at-0.0.0_development-py3.5.egg\damn_at\cli.py", line 105, in <lambda>
    args.store
  File "C:\Python351\lib\site-packages\damn_at-0.0.0_development-py3.5.egg\damn_at\cli.py", line 82, in analyze
    descr = analyzer.analyze_file(path)
  File "C:\Python351\lib\site-packages\damn_at-0.0.0_development-py3.5.egg\damn_at\analyzer.py", line 167, in analyze_file
    raise AnalyzerUnknownTypeException("E: Analyzer: No analyzer for %s (file: %s)" % (mimetype, an_uri))
damn_at.analyzer.AnalyzerUnknownTypeException: 'E: Analyzer: No analyzer for application/x-blender (file: ../peragro-test-files/mesh/blender/cube1.blend)'

**Comment by sueastside** [comment]
--store /tmp/peragro will obviously not work on windows. :)

Seems blender is not detected or something goes wrong in the plugin.

Can you run 'pt a --debug ../peragro-test-files/mesh/blender/cube1.blend --store c:/temp/' ?

**Comment by sagar-kohli** [comment]
@botanicvelious , @sueastside  There's no alternative of `grp module` for windows in `analyzer.py` file (https://github.com/peragro/peragro-at/blob/master/src/damn_at/analyzer.py). `grp` and `pwd` are not supported in windows. This could be one of the reasons that you are getting an error.

**Comment by botanicvelious** [comment]
> C:\development\peragro>pt -v a peragro-test-files\mesh\blender\cube1.blend
  DEBUG:yapsy: PluginFileLocator skips C:\Python351\lib\site-packages\damn_at-0.0.0_development-py3.5.egg\damn_at\repositories (not a directory)
  DEBUG:yapsy: PluginFileLocator walks (recursively) into directory: C:\Python351\lib\site-packages\yapsy-1.11.223-py3.5.egg\yapsy
  DEBUG:yapsy: AutoInstallPluginManager.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: compat.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: ConfigurablePluginManager.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: FilteredPluginManager.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: IMultiprocessChildPlugin.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: IPlugin.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: IPluginLocator.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: MultiprocessPluginManager.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: MultiprocessPluginProxy.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: PluginFileLocator.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: PluginInfo.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: PluginManager.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: PluginManagerDecorator.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: VersionedPluginManager.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: __init__.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: AutoInstallPluginManager.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: compat.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: ConfigurablePluginManager.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: FilteredPluginManager.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: IMultiprocessChildPlugin.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: IPlugin.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: IPluginLocator.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: MultiprocessPluginManager.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: MultiprocessPluginProxy.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: PluginFileLocator.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: PluginInfo.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: PluginManager.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: PluginManagerDecorator.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: VersionedPluginManager.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: __init__.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: PluginFileLocator skips C:\Python351\lib\site-packages\damn_at-0.0.0_development-py3.5.egg\damn_at\transcoders (not a directory)
  DEBUG:yapsy: PluginFileLocator walks (recursively) into directory: C:\Python351\lib\site-packages\damn_at-0.0.0_development-py3.5.egg\damn_at\analyzers
  DEBUG:yapsy: __init__.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: acoustid_analyzer.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: metadata.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: soxanalyzer.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: __init__.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: acoustid_analyzer.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: metadata.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: soxanalyzer.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: __init__.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: analyzerimage.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: analyzerimage_pil.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: metadata.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: __init__.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: analyzerimage.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: analyzerimage_pil.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: metadata.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: __init__.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: analyzerblend.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: analyzer_assimp.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: b-script-analyzerblend.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: metadata.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: __init__.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: analyzerblend.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: analyzer_assimp.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: b-script-analyzerblend.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: metadata.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: __init__.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: __init__.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: analyzertext.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: __init__.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: analyzertext.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: __init__.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: __init__.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: metadata.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: videoanalyzer.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: __init__.py is not a valid plugin for strategy info_ext
  DEBUG:yapsy: metadata.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: videoanalyzer.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: __init__.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:yapsy: __init__.cpython-35.pyc is not a valid plugin for strategy info_ext
  DEBUG:damn_at: PluginManagerSingleton initialised
Traceback (most recent call last):
  File "C:\Python351\Scripts\pt-script.py", line 11, in <module>
    load_entry_point('damn-at===0.0.0-development', 'console_scripts', 'pt')()
  File "C:\Python351\lib\site-packages\damn_at-0.0.0_development-py3.5.egg\damn_at\cli.py", line 349, in main
    args.func(args)
  File "C:\Python351\lib\site-packages\damn_at-0.0.0_development-py3.5.egg\damn_at\cli.py", line 105, in <lambda>
    args.store
  File "C:\Python351\lib\site-packages\damn_at-0.0.0_development-py3.5.egg\damn_at\cli.py", line 82, in analyze
    descr = analyzer.analyze_file(path)
  File "C:\Python351\lib\site-packages\damn_at-0.0.0_development-py3.5.egg\damn_at\analyzer.py", line 167, in analyze_file
    raise AnalyzerUnknownTypeException("E: Analyzer: No analyzer for %s (file: %s)" % (mimetype, an_uri))
damn_at.analyzer.AnalyzerUnknownTypeException: 'E: Analyzer: No analyzer for application/x-blender (file: peragro-test-files\\mesh\\blender\\cube1.blend)'

**Comment by botanicvelious** [comment]
Looks like this may be releated to #35

**Comment by sagar-kohli** [comment]
@botanicvelious `Repositories` directory doesnot exist. In `pluginmanager.py`, DAMNPluginManager class takes all the `directories_list` where it can find all the plugins. there's as such no plugin for `repository` and there's no `repositories` directory as well. Though it  should not be a big issue as `PluginFileLocator` is skipping it already.

**Comment by sagar-kohli** [comment]
@botanicvelious a bunch of code in `mimetypes.py` which im not getting is :<br \>
`search_paths = [path for path in sys.path[:] if path.find('damn_at') == -1]
file_handle, pathname, desc = imp.find_module('mimetypes', search_paths)
sys_mimetypes = imp.load_module('mimetypes', file_handle, pathname, desc)`
Is it pointing to itself ? As when I ran this code in the inspector it give me this error:<br \>
```File "mimetypes.py", line 22, in <module>
    sys_mimetypes = imp.load_module('mimetypes', file_handle, pathname, desc)
  File "mimetypes.py", line 22, in <module>
    sys_mimetypes = imp.load_module('mimetypes', file_handle, pathname, desc)
  File "mimetypes.py", line 22, in <module>
    sys_mimetypes = imp.load_module('mimetypes', file_handle, pathname, desc)
  File "mimetypes.py", line 22, in <module>
    sys_mimetypes = imp.load_module('mimetypes', file_handle, pathname, desc)
  File "mimetypes.py", line 22, in <module>
    sys_mimetypes = imp.load_module('mimetypes', file_handle, pathname, desc)
  File "mimetypes.py", line 22, in <module>
    sys_mimetypes = imp.load_module('mimetypes', file_handle, pathname, desc)
  File "mimetypes.py", line 8, in <module>
    import os
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by linganesan** [comment]
I had this same problem in fedora and I checkout the SOURCE.txt generated after the build in egg-info...
`setup.py
src/damn_at/__init__.py
src/damn_at/analyzer.py
src/damn_at/bld.py
src/damn_at/cli.py
src/damn_at/metadata.py
src/damn_at/metadatastore.py
src/damn_at/mimetypes.py
src/damn_at/options.py
src/damn_at/pluginmanager.py
src/damn_at/repository.py
src/damn_at/transcoder.py
src/damn_at/utilities.py
src/damn_at.egg-info/PKG-INFO
src/damn_at.egg-info/SOURCES.txt
src/damn_at.egg-info/dependency_links.txt
src/damn_at.egg-info/entry_points.txt
src/damn_at.egg-info/requires.txt
src/damn_at.egg-info/top_level.txt
src/damn_at/analyzers/__init__.py
src/damn_at/analyzers/audio/__init__.py
src/damn_at/analyzers/audio/acoustid_analyzer.py
src/damn_at/analyzers/audio/metadata.py
src/damn_at/analyzers/audio/soxanalyzer.py
src/damn_at/analyzers/image/__init__.py
src/damn_at/analyzers/image/analyzerimage.py
src/damn_at/analyzers/image/analyzerimage_pil.py
src/damn_at/analyzers/image/metadata.py
src/damn_at/analyzers/mesh/__init__.py
src/damn_at/analyzers/mesh/analyzer_assimp.py
src/damn_at/analyzers/mesh/analyzerblend.py
src/damn_at/analyzers/mesh/b-script-analyzerblend.py
src/damn_at/analyzers/mesh/metadata.py
src/damn_at/analyzers/text/__init__.py
src/damn_at/analyzers/text/plain/__init__.py
src/damn_at/analyzers/text/plain/analyzertext.py
src/damn_at/analyzers/video/__init__.py
src/damn_at/analyzers/video/metadata.py
src/damn_at/analyzers/video/videoanalyzer.py
src/damn_at/damnfs/__init__.py
src/damn_at/damnfs/damnfs.py
src/damn_at/damnfs/path.py
src/damn_at/serialization/__init__.py
src/damn_at/serialization/client.py
src/damn_at/serialization/server.py
src/damn_at/serialization/generated/__init__.py
src/damn_at/serialization/generated/damn/DamnService.py
src/damn_at/serialization/generated/damn/__init__.py
src/damn_at/serialization/generated/damn/constants.py
src/damn_at/serialization/generated/damn/ttypes.py
src/damn_at/serialization/generated/damn_types/__init__.py
src/damn_at/serialization/generated/damn_types/constants.py
src/damn_at/serialization/generated/damn_types/ttypes.py`

Plugin extension files and transcoders folder are missing! Missing of extension files could be reasonable but what on earth happened to transcoders dir? any ideas? Anyway it works fine after adding a MANIFEST.in file to support setup.py  :) PR #38
